#!/usr/bin/env python3
"""
Asynchronous comprehension function that returns
the first 10 numbers generated by async_generator.
"""
from 0-async_generator import async_generator
import typing


async def async_comprehension() -> typing.List[float]:
    """
    Asynchronous comprehension function that returns
    the first 10 random numbers generated by the
    async_generator.
    """
    random = [number async for number in async_generator()]
    return random[:10]
